name: Jetbrains-Help Docker Image CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }} 

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set registry environment variable
        run: echo "REGISTRY=ghcr.io" >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}:latest
          platforms: linux/amd64,linux/arm64

      - name: Install Docker Slim
        run: |
          LATEST_VERSION=$(curl -s https://api.github.com/repos/docker-slim/docker-slim/releases/latest | jq -r .tag_name)
          curl -sSL https://github.com/docker-slim/docker-slim/releases/download/$LATEST_VERSION/docker-slim-$LATEST_VERSION-linux-amd64.tar.gz | tar -xz -C /usr/local/bin

      - name: Slim the Docker image and Push
        env: 
          IMAGE: ${{ env.REGISTRY }}/${{ github.repository }}:latest
        run: |
          # docker pull ${{ env.IMAGE }}
          docker-slim build ${{ env.IMAGE }} --target ${{ env.REGISTRY }}/${{ github.repository }}:slim-latest --platform linux/amd64,linux/arm64 --tag ${{ env.REGISTRY }}/${{ github.repository }}:slim-latest
          docker push ${{ env.REGISTRY }}/${{ github.repository }}:slim-latest
